### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by imiroslavov** [dohnalik/sdr-widget-experimental-384#1]
https://github.com/dohnalik/sdr-widget-experimental-384/blob/fbcefc2f264b789eff9ff8b53cb2c0b817f28358/src/uac2_usb_specific_request.c#L124

Did You actually succeed with this?

**Comment by dohnalik** [comment]
Yes, its working, all that needs to be done is put 24.576 or 22.5... MHz
clock into the MCU clock block instead of the default 12/11M.

**Comment by imiroslavov** [comment]
Thanks for the quick response. 
24576 / 384 is 64 (both channels). Don't tell me You managed to get 32bit 384k.

**Comment by dohnalik** [comment]
Yes, I had it working. I even have working 768kHz 32 bit, but ot XMOS
platform with DSD1024. I left AVR32 as it didn't have the power anymore. To
get 384 working I had to overclock it from 66MHz (default audio-widget sys
freq) to 84 MHz (atmel says all chips can do 84MHz since some revision, so
its not really a overclock i guess) and I think B internal bus is running
on sysclk speed instead of sysclk/2. 384/32 bit is maximum this AVR32 can
do IMHO. Was a long time ago.

**Comment by dohnalik** [comment]
i described the changes needed on their google forum somewhere.

**Comment by imiroslavov** [comment]
That would be interesting read. 
384/32 is enough for me (it is an overkill anyway).

**Comment by imiroslavov** [comment]
Are there any significant changes in Your schematics?

**Comment by imiroslavov** [comment]
Here is a link to the original thread in case someone wants to build it. 
https://groups.google.com/forum/?hl=en#!searchin/audio-widget/384%7Csort:date/audio-widget/PyjAU1Fmyhg/L9cubFtOAwAJ
